// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDxAzfN4e9i0PJ4X5qCZf37_7AQqxIFA',
    appId: '1:104929393195:web:b6d084b46a20522753486e',
    messagingSenderId: '104929393195',
    projectId: 'appmed-6d031',
    authDomain: 'appmed-6d031.firebaseapp.com',
    storageBucket: 'appmed-6d031.firebasestorage.app',
    measurementId: 'G-BFK3FZ6FCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6TUj8YuBCXR7ArR6pLcm8pIRJwbN1tw',
    appId: '1:104929393195:android:3f7f4504a6d1974753486e',
    messagingSenderId: '104929393195',
    projectId: 'appmed-6d031',
    storageBucket: 'appmed-6d031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_EGNvE-MD8MFzpl3Me-1nuYJaeCV1_O0',
    appId: '1:104929393195:ios:386fec558a37b28253486e',
    messagingSenderId: '104929393195',
    projectId: 'appmed-6d031',
    storageBucket: 'appmed-6d031.firebasestorage.app',
    iosBundleId: 'com.example.medicoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_EGNvE-MD8MFzpl3Me-1nuYJaeCV1_O0',
    appId: '1:104929393195:ios:386fec558a37b28253486e',
    messagingSenderId: '104929393195',
    projectId: 'appmed-6d031',
    storageBucket: 'appmed-6d031.firebasestorage.app',
    iosBundleId: 'com.example.medicoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDDxAzfN4e9i0PJ4X5qCZf37_7AQqxIFA',
    appId: '1:104929393195:web:652cab99e29370b653486e',
    messagingSenderId: '104929393195',
    projectId: 'appmed-6d031',
    authDomain: 'appmed-6d031.firebaseapp.com',
    storageBucket: 'appmed-6d031.firebasestorage.app',
    measurementId: 'G-ZMPVS97LGJ',
  );
}
