name: medico_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado e Rotas
  go_router: ^14.1.2
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Utilitários UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  table_calendar: ^3.1.2
  
  # Seleção de Arquivos e Imagens
  image_picker: ^1.1.2
  file_picker: ^8.0.3

  # Mascaras e Campos de Texto
  mask_text_input_formatter: ^2.9.0
  intl_phone_field: ^3.2.0

  # Outros Utilitários
  connectivity_plus: ^6.0.3
  mime: ^1.0.5
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  intl: ^0.19.0
  
  # Mídia
  audioplayers: ^6.0.0
  gallery_saver: ^2.3.2
  record: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true