name: medico_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.1.2
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  mime: ^1.0.5

  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  connectivity_plus: ^6.0.3
  
  mask_text_input_formatter: ^2.9.0
  intl_phone_field: ^3.2.0

  image_picker: ^1.1.2
  file_picker: ^8.0.3

  url_launcher: ^6.3.0

  audioplayers: ^6.0.0
  gallery_saver: ^2.3.2
  dio: ^5.4.3+1 
  
  record: ^5.0.5

  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true